/**
 * AUTO-GENERATED by scripts/build-extension-worker.mjs
 *
 * Do NOT edit by hand. Rerun the script after changing
 * `extensionWorkerBootstrap.ts` or any of its imports to regenerate
 * the bundle.
 *
 * The string is the compiled, self-contained IIFE that runs inside
 * the extension sandbox worker. The host spawns a `Worker` from a
 * `Blob` URL wrapping this source.
 */

export const EXTENSION_WORKER_SOURCE = `"use strict";
(() => {
  // src/api/sandbox/types.ts
  var KNOWN_CAPABILITIES = [
    "ui:register-view",
    "ui:show-message",
    "ui:command-palette",
    "lang:register",
    "l10n:register",
    "commands:register",
    "commands:execute",
    "storage:read",
    "storage:write",
    "clipboard:write",
    "fs:read",
    "fs:write",
    "workspace:search",
    "workspace:info"
  ];
  function isKnownCapability(value) {
    return typeof value === "string" && KNOWN_CAPABILITIES.includes(value);
  }

  // src/api/sandbox/extensionWorkerBootstrap.ts
  var requestSeq = 0;
  var pending = /* @__PURE__ */ new Map();
  var views = /* @__PURE__ */ new Map();
  var l10nBundles = /* @__PURE__ */ new Map();
  var currentLocale = "en";
  var localeListeners = /* @__PURE__ */ new Set();
  var grantedCapabilities = /* @__PURE__ */ new Set();
  var extensionId = "";
  var renderingView = null;
  var effectQueue = [];
  function postToHost(message) {
    self.postMessage(message);
  }
  function request(capability, method, args) {
    if (!grantedCapabilities.has(capability)) {
      return Promise.reject(
        new Error(\`Capability '\${capability}' was not granted for this extension\`)
      );
    }
    const id = ++requestSeq;
    return new Promise((resolve, reject) => {
      pending.set(id, { resolve, reject });
      postToHost({
        kind: "worker:request",
        id,
        capability,
        method,
        args
      });
    });
  }
  function safeLog(level, args) {
    try {
      postToHost({ kind: "worker:log", level, args });
    } catch {
    }
  }
  function walkAndAssignHandlers(node, view) {
    const props = node.props ? { ...node.props } : void 0;
    if (props) {
      for (const key of ["onClick", "onChange", "onInput"]) {
        const handler = props[key];
        if (typeof handler === "function") {
          const handlerId = \`\${view.id}:\${++view.handlerSeq}\`;
          view.handlers.set(handlerId, handler);
          props[key] = handlerId;
        } else if (typeof handler !== "string") {
          delete props[key];
        }
      }
    }
    let children;
    if (Array.isArray(node.children)) {
      children = node.children.map((child) => {
        if (typeof child === "string" || typeof child === "number") return child;
        return walkAndAssignHandlers(child, view);
      });
    } else if (typeof node.children === "string" || typeof node.children === "number") {
      children = node.children;
    }
    return { tag: node.tag, key: node.key, props, children };
  }
  function renderView(view, options) {
    view.hookCursor = 0;
    view.handlers = /* @__PURE__ */ new Map();
    view.handlerSeq = 0;
    let schema;
    renderingView = view;
    try {
      schema = view.render({});
    } catch (e) {
      safeLog("error", [\`[view:\${view.id}] render threw\`, String(e?.message ?? e)]);
      schema = { tag: "div", children: "Extension render failed" };
    } finally {
      renderingView = null;
    }
    const prepared = walkAndAssignHandlers(schema, view);
    if (options.isInitial) {
      postToHost({
        kind: "worker:register-view",
        id: ++requestSeq,
        viewId: view.id,
        panel: view.panel,
        title: view.title,
        icon: view.icon,
        schema: prepared
      });
    } else {
      postToHost({
        kind: "worker:update-view",
        viewId: view.id,
        schema: prepared
      });
    }
    const effects = effectQueue.splice(0, effectQueue.length);
    for (const eff of effects) {
      try {
        eff();
      } catch (e) {
        safeLog("error", [\`[view:\${view.id}] effect threw\`, String(e?.message ?? e)]);
      }
    }
  }
  function useState(initial) {
    const view = renderingView;
    if (!view) {
      throw new Error("ui.useState can only be called inside a view's render function");
    }
    const cursor = view.hookCursor++;
    const existing = view.hooks[cursor];
    if (!existing) {
      view.hooks[cursor] = { kind: "state", value: initial };
    }
    const slot = view.hooks[cursor];
    const setter = (next) => {
      slot.value = next;
      queueMicrotaskOnce(view);
    };
    return [slot.value, setter];
  }
  var scheduledViews = /* @__PURE__ */ new Set();
  function queueMicrotaskOnce(view) {
    if (scheduledViews.has(view.id)) return;
    scheduledViews.add(view.id);
    queueMicrotask(() => {
      scheduledViews.delete(view.id);
      if (views.has(view.id)) {
        renderView(view, { isInitial: false });
      }
    });
  }
  function useEffect(effect, deps) {
    const view = renderingView;
    if (!view) {
      throw new Error("ui.useEffect can only be called inside a view's render function");
    }
    const cursor = view.hookCursor++;
    const prev = view.hooks[cursor];
    const shouldRun = !prev || !deps || !prev.deps || !depsEqual(prev.deps, deps);
    if (shouldRun) {
      effectQueue.push(() => {
        if (prev?.cleanup) {
          try {
            prev.cleanup();
          } catch (e) {
            safeLog("error", [\`[view:\${view.id}] effect cleanup threw\`, String(e?.message ?? e)]);
          }
        }
        const result = effect();
        const slot = {
          kind: "effect",
          deps,
          cleanup: typeof result === "function" ? result : void 0
        };
        view.hooks[cursor] = slot;
      });
    }
  }
  function depsEqual(a, b) {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
      if (!Object.is(a[i], b[i])) return false;
    }
    return true;
  }
  function buildCtx() {
    const registerView = (panel) => async (view) => {
      if (!view || typeof view !== "object" || typeof view.id !== "string" || typeof view.title !== "string") {
        throw new Error("registerView: invalid view descriptor");
      }
      if (typeof view.render !== "function") {
        throw new Error("registerView: \`render\` must be a function");
      }
      const existing = views.get(view.id);
      if (existing) {
        existing.render = view.render;
        existing.title = view.title;
        existing.panel = panel;
        existing.icon = view.icon ? { kind: "lucide", name: view.icon.name, size: view.icon.size, className: view.icon.className } : void 0;
        renderView(existing, { isInitial: false });
        return;
      }
      const state = {
        id: view.id,
        panel,
        title: view.title,
        icon: view.icon ? { kind: "lucide", name: view.icon.name, size: view.icon.size, className: view.icon.className } : void 0,
        render: view.render,
        hooks: [],
        hookCursor: 0,
        handlers: /* @__PURE__ */ new Map(),
        handlerSeq: 0
      };
      views.set(view.id, state);
      renderView(state, { isInitial: true });
    };
    return {
      commands: {
        registerCommand: (id, callback) => {
          const handlerId = \`command:\${id}\`;
          commandHandlers.set(handlerId, callback);
          return request("commands:register", "register", { id, handlerId });
        },
        executeCommand: (id, ...args) => request("commands:execute", "execute", { id, args })
      },
      window: {
        registerRightPanelView: registerView("right"),
        registerLeftPanelView: registerView("left"),
        showInformationMessage: (msg) => request("ui:show-message", "showInformationMessage", { message: String(msg) })
      },
      l10n: {
        registerTranslations: async (locale, bundle) => {
          const existing = l10nBundles.get(locale) ?? {};
          l10nBundles.set(locale, { ...existing, ...bundle });
          for (const fn of localeListeners) {
            try {
              fn();
            } catch {
            }
          }
          await request("l10n:register", "register", { locale, bundle });
        },
        t: (key, params) => {
          const bundle = l10nBundles.get(currentLocale) ?? l10nBundles.get("en") ?? {};
          let text = bundle[key] || key;
          if (params) {
            for (const [k, v] of Object.entries(params)) {
              text = text.replace(new RegExp(\`\\\\{\${k}\\\\}\`, "g"), v);
            }
          }
          return text;
        },
        getLocale: () => currentLocale,
        subscribe: (listener) => {
          localeListeners.add(listener);
          return () => localeListeners.delete(listener);
        }
      },
      languages: {
        register: (language) => request("lang:register", "register", language),
        setMonarchTokens: (id, rules) => request("lang:register", "setMonarchTokens", { id, rules }),
        setConfiguration: (id, config) => request("lang:register", "setConfiguration", { id, config }),
        setIndentation: (id, options) => request("lang:register", "setIndentation", { id, options })
      },
      storage: {
        get: (key, defaultValue) => request("storage:read", "get", { key, defaultValue }),
        set: (key, value) => request("storage:write", "set", { key, value })
      },
      clipboard: {
        writeText: (text) => request("clipboard:write", "writeText", { text })
      },
      workspace: {
        readFile: (path) => request("fs:read", "readFile", { path }),
        writeFile: (path, content) => request("fs:write", "writeFile", { path, content }),
        search: (query) => request("workspace:search", "search", { query }),
        info: () => request("workspace:info", "info", {})
      },
      ui: {
        useState,
        useEffect
      }
    };
  }
  var commandHandlers = /* @__PURE__ */ new Map();
  async function handleInit(msg) {
    extensionId = msg.extensionId;
    grantedCapabilities = new Set(msg.grantedCapabilities);
    currentLocale = msg.locale;
    const ctx = buildCtx();
    try {
      const g = self;
      const neutralise = (name) => {
        try {
          Object.defineProperty(g, name, {
            value: () => {
              throw new Error(\`\${name} is not available inside the extension sandbox\`);
            },
            configurable: false,
            writable: false
          });
        } catch {
        }
      };
      neutralise("fetch");
      neutralise("XMLHttpRequest");
      neutralise("importScripts");
      neutralise("WebSocket");
      neutralise("EventSource");
    } catch (e) {
      safeLog("warn", ["Failed to neutralise globals", String(e?.message ?? e)]);
    }
    try {
      const moduleObj = { exports: {} };
      const runner = new Function(
        "module",
        "exports",
        "ctx",
        "console",
        msg.script
      );
      const guestConsole = {
        log: (...args) => safeLog("debug", args),
        debug: (...args) => safeLog("debug", args),
        info: (...args) => safeLog("debug", args),
        warn: (...args) => safeLog("warn", args),
        error: (...args) => safeLog("error", args)
      };
      runner(moduleObj, moduleObj.exports, ctx, guestConsole);
      const activate = moduleObj.exports.activate ?? moduleObj.exports.default?.activate;
      if (typeof activate === "function") {
        await activate(ctx);
      } else {
        safeLog("warn", [\`[\${extensionId}] extension did not export an \\\`activate\\\` function\`]);
      }
      postToHost({ kind: "worker:ready", ok: true });
    } catch (e) {
      const err = e;
      postToHost({
        kind: "worker:ready",
        ok: false,
        error: { name: err?.name ?? "Error", message: err?.message ?? String(e) }
      });
    }
  }
  function handleResponse(msg) {
    const resolver = pending.get(msg.id);
    if (!resolver) return;
    pending.delete(msg.id);
    if (msg.kind === "host:response" && msg.ok) {
      resolver.resolve(msg.value);
    } else if (msg.kind === "host:error") {
      const err = new Error(msg.error.message);
      err.name = msg.error.name;
      resolver.reject(err);
    }
  }
  function handleHostEvent(msg) {
    if (msg.topic === "locale-changed" && typeof msg.payload === "string") {
      currentLocale = msg.payload;
      for (const listener of localeListeners) {
        try {
          listener();
        } catch {
        }
      }
      for (const view of views.values()) {
        renderView(view, { isInitial: false });
      }
    }
  }
  function handleUiEvent(msg) {
    const handlerId = msg.handlerId;
    if (handlerId.startsWith("command:")) {
      const cmdHandler = commandHandlers.get(handlerId);
      if (cmdHandler) {
        try {
          cmdHandler(...Array.isArray(msg.args) ? msg.args : []);
        } catch (e) {
          safeLog("error", [\`[command] handler threw\`, String(e?.message ?? e)]);
        }
      }
      return;
    }
    const colon = handlerId.indexOf(":");
    if (colon < 0) return;
    const viewId = handlerId.slice(0, colon);
    const view = views.get(viewId);
    const handler = view?.handlers.get(handlerId);
    if (!handler) return;
    try {
      handler(...Array.isArray(msg.args) ? msg.args : []);
    } catch (e) {
      safeLog("error", [\`[view:\${viewId}] handler threw\`, String(e?.message ?? e)]);
    }
  }
  self.addEventListener("message", (event) => {
    const msg = event.data;
    if (!msg || typeof msg !== "object" || typeof msg.kind !== "string") {
      return;
    }
    switch (msg.kind) {
      case "host:init":
        if (extensionId) {
          safeLog("warn", ["host:init received twice \\u2014 ignoring"]);
          return;
        }
        {
          const filtered = (msg.grantedCapabilities || []).filter(isKnownCapability);
          handleInit({ ...msg, grantedCapabilities: filtered });
        }
        break;
      case "host:response":
      case "host:error":
        handleResponse(msg);
        break;
      case "host:event":
        handleHostEvent(msg);
        break;
      case "host:ui-event":
        handleUiEvent(msg);
        break;
    }
  });
  self.addEventListener("error", (event) => {
    safeLog("error", [
      "Uncaught error in extension",
      event.message,
      event.filename,
      event.lineno,
      event.colno
    ]);
  });
  self.addEventListener("unhandledrejection", (event) => {
    safeLog("error", ["Unhandled promise rejection", String(event.reason)]);
  });
})();
`;
